try {
    console.log(algo);
}
catch(e) {
    throw new Error(e + ", algo de errado nn est√° certo");
}